### ISSUE TITLE
日期与时间显示存在问题

### ISSUE THREAD

**Issue by EliotChen8** [Ben-Jamin-Wong/SUSTechGate#1]
可通行一栏有效期结束日期显示错误、结束时间早于开始时间，望修改QAQ。

![Screenshot](https://user-images.githubusercontent.com/103273258/199951732-cc77d961-c096-4bd5-867f-a23e3e023717.jpg)

**Comment by Ben-Jamin-Wong** [comment]
> 可通行一栏有效期结束日期显示错误、结束时间早于开始时间，望修改QAQ。
> 
> ![Screenshot](https://user-images.githubusercontent.com/103273258/199951732-cc77d961-c096-4bd5-867f-a23e3e023717.jpg)

该问题已经通过修改HTML修复。
（本项目搬运https://github.com/SUSTechGate/run）

**Comment by EliotChen8** [comment]
请问修改后的成果如何访问😭
之前的网址进入以后依然存在问题😭😭

**Comment by EliotChen8** [comment]
感激不尽！你是你是口罩时代的英雄，南柯不会忘记！
